// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Acme.V1Alpha3
{

    [OutputType]
    public sealed class ChallengeSpecSolverDns01Acmedns
    {
        /// <summary>
        /// A reference to a specific 'key' within a Secret resource. In some instances, `key` is a required field.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Acme.V1Alpha3.ChallengeSpecSolverDns01AcmednsAccountSecretRef AccountSecretRef;
        public readonly string Host;

        [OutputConstructor]
        private ChallengeSpecSolverDns01Acmedns(
            Pulumi.Kubernetes.Types.Outputs.Acme.V1Alpha3.ChallengeSpecSolverDns01AcmednsAccountSecretRef accountSecretRef,

            string host)
        {
            AccountSecretRef = accountSecretRef;
            Host = host;
        }
    }
}
