// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Certmanager.V1
{

    [OutputType]
    public sealed class ClusterIssuerSpecAcmeExternalAccountBinding
    {
        /// <summary>
        /// keyAlgorithm is the MAC key algorithm that the key is used for. Valid values are "HS256", "HS384" and "HS512".
        /// </summary>
        public readonly string KeyAlgorithm;
        /// <summary>
        /// keyID is the ID of the CA key that the External Account is bound to.
        /// </summary>
        public readonly string KeyID;
        /// <summary>
        /// keySecretRef is a Secret Key Selector referencing a data item in a Kubernetes Secret which holds the symmetric MAC key of the External Account Binding. The `key` is the index string that is paired with the key data in the Secret and should not be confused with the key data itself, or indeed with the External Account Binding keyID above. The secret key stored in the Secret **must** be un-padded, base64 URL encoded data.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1.ClusterIssuerSpecAcmeExternalAccountBindingKeySecretRef KeySecretRef;

        [OutputConstructor]
        private ClusterIssuerSpecAcmeExternalAccountBinding(
            string keyAlgorithm,

            string keyID,

            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1.ClusterIssuerSpecAcmeExternalAccountBindingKeySecretRef keySecretRef)
        {
            KeyAlgorithm = keyAlgorithm;
            KeyID = keyID;
            KeySecretRef = keySecretRef;
        }
    }
}
