// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Beta1
{

    [OutputType]
    public sealed class IssuerSpecVenafi
    {
        /// <summary>
        /// Cloud specifies the Venafi cloud configuration settings. Only one of TPP or Cloud may be specified.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Beta1.IssuerSpecVenafiCloud Cloud;
        /// <summary>
        /// TPP specifies Trust Protection Platform configuration settings. Only one of TPP or Cloud may be specified.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Beta1.IssuerSpecVenafiTpp Tpp;
        /// <summary>
        /// Zone is the Venafi Policy Zone to use for this issuer. All requests made to the Venafi platform will be restricted by the named zone policy. This field is required.
        /// </summary>
        public readonly string Zone;

        [OutputConstructor]
        private IssuerSpecVenafi(
            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Beta1.IssuerSpecVenafiCloud cloud,

            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Beta1.IssuerSpecVenafiTpp tpp,

            string zone)
        {
            Cloud = cloud;
            Tpp = tpp;
            Zone = zone;
        }
    }
}
