// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2
{

    [OutputType]
    public sealed class IssuerSpecVaultAuthAppRole
    {
        /// <summary>
        /// Path where the App Role authentication backend is mounted in Vault, e.g: "approle"
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// RoleID configured in the App Role authentication backend when setting up the authentication backend in Vault.
        /// </summary>
        public readonly string RoleId;
        /// <summary>
        /// Reference to a key in a Secret that contains the App Role secret used to authenticate with Vault. The `key` field must be specified and denotes which entry within the Secret resource is used as the app role secret.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthAppRoleSecretRef SecretRef;

        [OutputConstructor]
        private IssuerSpecVaultAuthAppRole(
            string path,

            string roleId,

            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthAppRoleSecretRef secretRef)
        {
            Path = path;
            RoleId = roleId;
            SecretRef = secretRef;
        }
    }
}
