// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2
{

    [OutputType]
    public sealed class IssuerSpecVaultAuth
    {
        /// <summary>
        /// AppRole authenticates with Vault using the App Role auth mechanism, with the role and secret stored in a Kubernetes Secret resource.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthAppRole AppRole;
        /// <summary>
        /// Kubernetes authenticates with Vault by passing the ServiceAccount token stored in the named Secret resource to the Vault server.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthKubernetes Kubernetes;
        /// <summary>
        /// TokenSecretRef authenticates with Vault by presenting a token.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthTokenSecretRef TokenSecretRef;

        [OutputConstructor]
        private IssuerSpecVaultAuth(
            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthAppRole appRole,

            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthKubernetes kubernetes,

            Pulumi.Kubernetes.Types.Outputs.Certmanager.V1Alpha2.IssuerSpecVaultAuthTokenSecretRef tokenSecretRef)
        {
            AppRole = appRole;
            Kubernetes = kubernetes;
            TokenSecretRef = tokenSecretRef;
        }
    }
}
